# Create a matrix of embeddings for every case

from webbrowser import get
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd
from openai import AzureOpenAI
import json

df = [
    [1000001, "Patient presents with erythematous, pruritic plaques on extensor surfaces. Differential diagnosis includes psoriasis, eczema, and tinea corporis. Examination reveals well-demarcated, silver-scaled lesions characteristic of chronic plaque psoriasis. No systemic symptoms reported. History of similar lesions during winter months.", "Initial treatment with topical corticosteroids suggested. Follow-up in two weeks for reassessment. Considering phototherapy if no improvement. Patient advised to moisturize regularly. Educate about potential triggers and adherence to treatment plan."],
    [1000002, "Middle-aged female with a persistent, non-healing ulcer on the lower leg. Lesion measures 2cm in diameter, with a raised, rolled border. Suspected basal cell carcinoma. No significant past medical history. Biopsy recommended to confirm diagnosis. Educate patient on sun protection and regular skin checks.", "Appointment for biopsy scheduled. Patient expressed concern about scarring. Reassured about minimal scarring techniques. Emphasized the importance of early detection and treatment. Discussed options for potential excision and follow-up care."],
    [1000003, "Teenager with a widespread, pustular eruption on the face, chest, and back. Diagnosis: severe nodulocystic acne. Not responsive to over-the-counter treatments. Considering isotretinoin therapy. No contraindications noted. Blood tests ordered to evaluate liver function before starting treatment.", "Informed consent for isotretinoin obtained. Side effects and pregnancy prevention discussed in detail. Next appointment set for one month to monitor progress and side effects. Encouraged use of non-comedogenic skin care products."],
    [1000004, "Elderly male with a rapidly enlarging, ulcerated nodule on the scalp. Lesion bleeds easily with minor trauma. Clinical suspicion of squamous cell carcinoma. Recommending urgent excision and biopsy to prevent further spread. Patient advised on wound care post-procedure.", "Urgent excision scheduled for the following week. Provided preoperative instructions and wound care guidelines. Discussed the possibility of additional treatments based on biopsy results. Patient reassured about the procedure and expected outcomes."],
    [1000005, "Young adult with chronic atopic dermatitis presenting with severe itching and lichenification. Lesions located on flexural areas. Currently using topical steroids with limited relief. Consideration for systemic treatment with immunomodulators. Educate on skin care routines and trigger avoidance.", "Discussion on starting systemic immunomodulators conducted. Patient educated about potential side effects and monitoring requirements. Advised to continue current skin care regimen and avoid known triggers. Follow-up appointment in one month to assess effectiveness."],
    [1000006, "Middle-aged male presenting with a solitary, hyperpigmented macule on the back. No associated symptoms. Differential includes lentigo, seborrheic keratosis, and melanoma. Dermoscopic examination suggested for further evaluation. Patient educated on signs of malignant transformation.", "Dermoscopic examination scheduled. Patient informed about the procedure and its importance. Advised to monitor for changes in the lesion and report immediately. Follow-up appointment in two weeks to discuss dermoscopy results."],
    [1000007, "Child with multiple erythematous, crusted lesions on the face and limbs. History of atopic dermatitis. Current lesions suspected to be impetigo. Swabs taken for bacterial culture. Starting empirical antibiotic treatment. Educate on hygiene and avoiding scratching.", "Antibiotic prescription provided. Emphasized the importance of completing the full course. Instructed on hygiene practices to prevent spread. Follow-up in one week to assess response to treatment and review culture results. Advised on managing itching and preventing secondary infection."],
    [1000008, "Young female with a symmetrical, hyperpigmented rash on the cheeks and nose. Likely diagnosis: melasma. No history of systemic disease. Treatment options discussed including topical depigmenting agents and sun protection measures. Advise on avoiding sun exposure.", "Prescription for topical depigmenting cream provided. Emphasized strict sun protection measures. Advised on the gradual nature of treatment response. Follow-up in one month to evaluate effectiveness and discuss potential additional treatments if necessary."],
    [1000009, "Elderly female with multiple, flesh-colored papules on the neck and axillae. Clinical diagnosis: acrochordons (skin tags). No associated symptoms. Considering removal for cosmetic reasons. Educate on available removal methods: cryotherapy, excision, or ligation.", "Patient opted for cryotherapy. Procedure scheduled for next week. Explained the process and expected healing time. Discussed aftercare and signs of potential complications. Follow-up appointment in two weeks to check healing and remove any remaining tags."],
    [1000010, "Teenage male with a persistent, itchy rash on the scalp and neck. Lesions are erythematous with overlying scales. Likely diagnosis: seborrheic dermatitis. History of similar episodes. Prescribing antifungal shampoo and topical corticosteroids. Educate on chronic nature and management.", "Antifungal shampoo and topical corticosteroid prescription provided. Explained proper use and application. Advised to avoid scratching and maintain scalp hygiene. Follow-up in two weeks to assess treatment response and make any necessary adjustments."],
    [1000011, "Middle-aged female with multiple, itchy, vesicular eruptions on the hands and feet. Suspected dyshidrotic eczema. Lesions are pruritic and recurrent. Prescribing high-potency topical corticosteroids and advising on avoiding potential triggers. Patient educated on proper skin care.", "Topical corticosteroid prescription provided. Discussed potential triggers and avoidance strategies. Emphasized regular moisturizing and gentle skin care. Follow-up in two weeks to assess response to treatment and adjust as necessary."],
    [1000012, "Elderly male presenting with a non-healing, ulcerated lesion on the lower lip. High suspicion for squamous cell carcinoma. Lesion is firm with a raised border. Immediate biopsy recommended. Educate on risk factors including sun exposure and smoking history.", "Biopsy scheduled for the next available appointment. Patient informed about the procedure and its importance. Advised on wound care post-biopsy. Discussed potential treatment options based on biopsy results. Follow-up appointment in one week to review findings."],
    [1000013, "Young adult male with clusters of vesicles and erythema on the left side of the chest. Suspected herpes zoster. Patient reports localized burning pain and previous history of chickenpox. Initiating antiviral therapy. Educate on preventing spread and managing pain.", "Antiviral prescription provided. Pain management discussed, including over-the-counter pain relief and potential use of nerve pain medications if necessary. Advised on maintaining hygiene and preventing contact with others to avoid spread. Follow-up in one week to monitor healing and pain control."],
    [1000014, "Middle-aged female presenting with multiple erythematous nodules on the shins. Suspected erythema nodosum. Associated with recent streptococcal throat infection. Recommend throat culture and supportive care including NSAIDs and rest. Educate on potential triggers and symptom management.", "Throat culture ordered. NSAID prescription provided for pain and inflammation. Advised to rest and elevate legs. Follow-up in two weeks to review throat culture results and assess symptom improvement. Discussed potential need for further investigation if no improvement."],
    [1000015, "Teenager with widespread erythematous, scaly patches on the scalp and face. Suspected seborrheic dermatitis. Prescribing antifungal shampoo and low-potency topical corticosteroids. Educate on regular scalp hygiene and avoiding potential irritants.", "Antifungal shampoo and topical corticosteroid prescription provided. Explained proper application and frequency of use. Advised to maintain scalp hygiene and avoid harsh hair products. Follow-up in two weeks to assess treatment response and adjust regimen if necessary."],
    [1000016, "Elderly male with thickened, discolored toenails. Likely diagnosis: onychomycosis. Patient reports difficulty trimming nails and occasional pain. Recommend nail clipping and topical antifungal treatment. Educate on foot hygiene and regular monitoring.", "Topical antifungal treatment provided. Advised on proper nail clipping techniques and regular foot hygiene. Discussed the chronic nature of the condition and importance of adherence to treatment. Follow-up in one month to assess nail improvement and discuss potential systemic treatment if needed."],
    [1000017, "Middle-aged male presenting with a solitary, pearly papule on the forehead. Clinical suspicion of basal cell carcinoma. Recommend excision and biopsy. Educate on sun protection and importance of regular skin checks.", "Excision and biopsy scheduled. Patient informed about the procedure and minimal scarring techniques. Emphasized the importance of sun protection measures and regular dermatological check-ups. Follow-up appointment in two weeks to review biopsy results and discuss further management if necessary."],
    [1000018, "Young female with recurrent painful cysts on the axillae. Likely diagnosis: hidradenitis suppurativa. No significant past medical history. Prescribing topical clindamycin and recommending lifestyle modifications. Educate on chronic nature and trigger avoidance.", "Topical clindamycin prescription provided. Discussed lifestyle modifications including weight management and avoiding tight clothing. Advised on proper hygiene and potential use of warm compresses for pain relief. Follow-up in one month to assess response and discuss further treatment options if needed."],
    [1000019, "Teenager with multiple inflamed comedones and pustules on the face and upper back. Diagnosis: moderate to severe acne vulgaris. Considering oral antibiotics. Educate on skincare routine and avoiding picking at lesions.", "Oral antibiotic prescription provided. Discussed proper skincare routine including gentle cleansing and use of non-comedogenic products. Emphasized the importance of not picking at lesions to prevent scarring. Follow-up in one month to monitor response and adjust treatment if necessary."],
    [1000020, "Elderly female with a rapidly growing, non-pigmented nodule on the cheek. Clinical suspicion of squamous cell carcinoma. Recommend urgent biopsy and excision. Educate on sun protection and regular skin examinations.", "Urgent biopsy and excision scheduled. Patient informed about the procedure and potential outcomes. Emphasized the importance of sun protection and regular dermatological follow-ups. Follow-up appointment in one week to review biopsy results and discuss further management if needed."],
    [1000021, "Middle-aged male with chronic, itchy plaques on the elbows and knees. Likely diagnosis: chronic plaque psoriasis. History of intermittent flares. Prescribing high-potency topical corticosteroids and advising on regular emollient use.", "High-potency topical corticosteroid prescription provided. Discussed regular use of emollients and avoidance of known triggers. Follow-up in two weeks to assess treatment response and discuss potential phototherapy if no improvement. Educated on chronic nature and importance of treatment adherence."],
    [1000022, "Young adult female with painful, erythematous nodules on the legs. Suspected erythema nodosum secondary to recent upper respiratory infection. Recommend supportive care including NSAIDs and rest. Educate on potential triggers and symptom management.", "NSAID prescription provided for pain and inflammation. Advised to rest and elevate legs. Follow-up in two weeks to assess symptom improvement. Discussed potential need for further investigation if symptoms persist."],
    [1000023, "Elderly male with a non-healing ulcerated lesion on the ear. High suspicion for squamous cell carcinoma. Recommend urgent biopsy and excision. Educate on risk factors including sun exposure and smoking.", "Urgent biopsy and excision scheduled. Patient informed about the procedure and importance of early detection and treatment. Advised on wound care post-procedure. Follow-up appointment in one week to review biopsy results and discuss further management if necessary."],
    [1000024, "Teenager with widespread, erythematous pustules on the face and trunk. Diagnosis: severe acne vulgaris. Not responsive to topical treatments. Considering oral isotretinoin. Educate on potential side effects and pregnancy prevention measures.", "Informed consent for isotretinoin obtained. Side effects and pregnancy prevention discussed in detail. Blood tests ordered to evaluate liver function before starting treatment. Follow-up in one month to monitor progress and side effects. Encouraged use of non-comedogenic skincare products."],
    [1000025, "Middle-aged female with multiple hyperpigmented macules on the forearms. Suspected solar lentigines. No associated symptoms. Recommend sun protection measures and considering topical treatments for cosmetic improvement.", "Prescription for topical depigmenting cream provided. Emphasized strict sun protection measures. Advised on gradual nature of treatment response. Follow-up in one month to evaluate effectiveness and discuss potential additional treatments if necessary."],
    [1000026, "Young adult male with a single, firm, painless nodule on the scalp. Suspected epidermoid cyst. No associated symptoms. Recommend excision for definitive diagnosis and cosmetic reasons.", "Excision scheduled for next week. Explained the process and expected healing time. Discussed aftercare and signs of potential complications. Follow-up appointment in two weeks to check healing and review histopathology results."],
    [1000027, "Elderly female with multiple flesh-colored papules on the neck. Clinical diagnosis: acrochordons (skin tags). No associated symptoms. Considering removal for cosmetic reasons. Educate on available removal methods: cryotherapy, excision, or ligation.", "Patient opted for cryotherapy. Procedure scheduled for next week. Explained the process and expected healing time. Discussed aftercare and signs of potential complications. Follow-up appointment in two weeks to check healing and remove any remaining tags."],
    [1000028, "Teenager with a persistent, pruritic rash on the face and neck. Lesions are erythematous with fine scales. Likely diagnosis: atopic dermatitis. Prescribing topical corticosteroids and advising on skincare routine and trigger avoidance.", "Topical corticosteroid prescription provided. Discussed proper skincare routine including regular moisturizing and avoiding known triggers. Advised on the importance of adherence to treatment plan. Follow-up in two weeks to assess response and adjust treatment if necessary."],
    [1000029, "Middle-aged male with a solitary, hyperpigmented macule on the back. No associated symptoms. Differential includes lentigo, seborrheic keratosis, and melanoma. Dermoscopic examination suggested for further evaluation. Patient educated on signs of malignant transformation.", "Dermoscopic examination scheduled. Patient informed about the procedure and its importance. Advised to monitor for changes in the lesion and report immediately. Follow-up appointment in two weeks to discuss dermoscopy results."],
    [1000030, "Elderly male with a rapidly enlarging, ulcerated nodule on the scalp. Lesion bleeds easily with minor trauma. Clinical suspicion of squamous cell carcinoma. Recommending urgent excision and biopsy to prevent further spread. Patient advised on wound care post-procedure.", "Urgent excision scheduled for the following week. Provided preoperative instructions and wound care guidelines. Discussed the possibility of additional treatments based on biopsy results. Patient reassured about the procedure and expected outcomes."],
    [1000031, "Middle-aged female with a persistent, non-healing ulcer on the lower leg. Lesion measures 2cm in diameter, with a raised, rolled border. Suspected basal cell carcinoma. No significant past medical history. Biopsy recommended to confirm diagnosis. Educate patient on sun protection and regular skin checks.", "Appointment for biopsy scheduled. Patient expressed concern about scarring. Reassured about minimal scarring techniques. Emphasized the importance of early detection and treatment. Discussed options for potential excision and follow-up care."],
    [1000033, "Young adult female with hyperpigmented patches on the face, particularly on the cheeks and forehead. Diagnosis: melasma. No significant medical history. Recommend topical depigmenting agents and strict sun protection. Educate on avoiding sun exposure.", "Prescription for topical depigmenting cream provided. Emphasized the importance of sun protection measures including daily sunscreen use. Advised that treatment response may be gradual. Follow-up in one month to evaluate effectiveness and consider additional treatments if necessary."],
    [1000034, "Teenager with a chronic itchy rash on the scalp and neck. Lesions are erythematous with overlying scales. Likely diagnosis: seborrheic dermatitis. Prescribing antifungal shampoo and topical corticosteroids. Educate on chronic nature and management.", "Antifungal shampoo and topical corticosteroid prescription provided. Explained proper use and application. Advised to avoid scratching and maintain scalp hygiene. Follow-up in two weeks to assess treatment response and make any necessary adjustments."],
    [1000035, "Middle-aged female with multiple, itchy, vesicular eruptions on the hands and feet. Suspected dyshidrotic eczema. Lesions are pruritic and recurrent. Prescribing high-potency topical corticosteroids and advising on avoiding potential triggers. Patient educated on proper skin care.", "Topical corticosteroid prescription provided. Discussed potential triggers and avoidance strategies. Emphasized regular moisturizing and gentle skin care. Follow-up in two weeks to assess response to treatment and adjust as necessary."],
    [1000036, "Elderly male presenting with a non-healing, ulcerated lesion on the lower lip. High suspicion for squamous cell carcinoma. Lesion is firm with a raised border. Immediate biopsy recommended. Educate on risk factors including sun exposure and smoking history.", "Biopsy scheduled for the next available appointment. Patient informed about the procedure and its importance. Advised on wound care post-biopsy. Discussed potential treatment options based on biopsy results. Follow-up appointment in one week to review findings."],
    [1000037, "Young adult female with chronic atopic dermatitis presenting with severe itching and lichenification. Lesions located on flexural areas. Currently using topical steroids with limited relief. Consideration for systemic treatment with immunomodulators. Educate on skin care routines and trigger avoidance.", "Discussion on starting systemic immunomodulators conducted. Patient educated about potential side effects and monitoring requirements. Advised to continue current skin care regimen and avoid known triggers. Follow-up appointment in one month to assess effectiveness."],
    [1000038, "Middle-aged male with a solitary, hyperpigmented macule on the back. No associated symptoms. Differential includes lentigo, seborrheic keratosis, and melanoma. Dermoscopic examination suggested for further evaluation. Patient educated on signs of malignant transformation.", "Dermoscopic examination scheduled. Patient informed about the procedure and its importance. Advised to monitor for changes in the lesion and report immediately. Follow-up appointment in two weeks to discuss dermoscopy results."],
    [1000039, "Child with multiple erythematous, crusted lesions on the face and limbs. History of atopic dermatitis. Current lesions suspected to be impetigo. Swabs taken for bacterial culture. Starting empirical antibiotic treatment. Educate on hygiene and avoiding scratching.", "Antibiotic prescription provided. Emphasized the importance of completing the full course. Instructed on hygiene practices to prevent spread. Follow-up in one week to assess response to treatment and review culture results. Advised on managing itching and preventing secondary infection."],
    [1000040, "Young adult male presenting with multiple flesh-colored papules on the neck and axillae. Clinical diagnosis: acrochordons (skin tags). No associated symptoms. Considering removal for cosmetic reasons. Educate on available removal methods: cryotherapy, excision, or ligation.", "Patient opted for cryotherapy. Procedure scheduled for next week. Explained the process and expected healing time. Discussed aftercare and signs of potential complications. Follow-up appointment in two weeks to check healing and remove any remaining tags."],
    [1000041, "Elderly female with a rapidly enlarging, ulcerated nodule on the scalp. Lesion bleeds easily with minor trauma. Clinical suspicion of squamous cell carcinoma. Recommending urgent excision and biopsy to prevent further spread. Patient advised on wound care post-procedure.", "Urgent excision scheduled for the following week. Provided preoperative instructions and wound care guidelines. Discussed the possibility of additional treatments based on biopsy results. Patient reassured about the procedure and expected outcomes."],
    [1000042, "Middle-aged female presenting with multiple erythematous nodules on the shins. Suspected erythema nodosum. Associated with recent streptococcal throat infection. Recommend throat culture and supportive care including NSAIDs and rest. Educate on potential triggers and symptom management.", "Throat culture ordered. NSAID prescription provided for pain and inflammation. Advised to rest and elevate legs. Follow-up in two weeks to review throat culture results and assess symptom improvement. Discussed potential need for further investigation if no improvement."],
    [1000043, "Teenager with multiple inflamed comedones and pustules on the face and upper back. Diagnosis: moderate to severe acne vulgaris. Considering oral antibiotics. Educate on skincare routine and avoiding picking at lesions.", "Oral antibiotic prescription provided. Discussed proper skincare routine including gentle cleansing and use of non-comedogenic products. Emphasized the importance of not picking at lesions to prevent scarring. Follow-up in one month to monitor response and adjust treatment if necessary."],
    [1000044, "Middle-aged male with a solitary, pearly papule on the forehead. Clinical suspicion of basal cell carcinoma. Recommend excision and biopsy. Educate on sun protection and importance of regular skin checks.", "Excision and biopsy scheduled. Patient informed about the procedure and minimal scarring techniques. Emphasized the importance of sun protection measures and regular dermatological check-ups. Follow-up appointment in two weeks to review biopsy results and discuss further management if necessary."],
    [1000045, "Young adult female with painful, erythematous nodules on the legs. Suspected erythema nodosum secondary to recent upper respiratory infection. Recommend supportive care including NSAIDs and rest. Educate on potential triggers and symptom management.", "NSAID prescription provided for pain and inflammation. Advised to rest and elevate legs. Follow-up in two weeks to assess symptom improvement. Discussed potential need for further investigation if symptoms persist."],
    [1000046, "Middle-aged male with multiple hyperpigmented macules on the forearms. Suspected solar lentigines. No associated symptoms. Recommend sun protection measures and considering topical treatments for cosmetic improvement.", "Prescription for topical depigmenting cream provided. Emphasized strict sun protection measures. Advised on gradual nature of treatment response. Follow-up in one month to evaluate effectiveness and discuss potential additional treatments if necessary."],
    [1000047, "Teenager with a persistent, pruritic rash on the face and neck. Lesions are erythematous with fine scales. Likely diagnosis: atopic dermatitis. Prescribing topical corticosteroids and advising on skincare routine and trigger avoidance.", "Topical corticosteroid prescription provided. Discussed proper skincare routine including regular moisturizing and avoiding known triggers. Advised on the importance of adherence to treatment plan. Follow-up in two weeks to assess response and adjust treatment if necessary."],
    [1000048, "Middle-aged female with chronic itchy plaques on the elbows and knees. Likely diagnosis: chronic plaque psoriasis. History of intermittent flares. Prescribing high-potency topical corticosteroids and advising on regular emollient use.", "High-potency topical corticosteroid prescription provided. Discussed regular use of emollients and avoidance of known triggers. Follow-up in two weeks to assess treatment response and discuss potential phototherapy if no improvement. Educated on chronic nature and importance of treatment adherence."],
    [1000049, "Elderly male with thickened, discolored toenails. Likely diagnosis: onychomycosis. Patient reports difficulty trimming nails and occasional pain. Recommend nail clipping and topical antifungal treatment. Educate on foot hygiene and regular monitoring.", "Topical antifungal treatment provided. Advised on proper nail clipping techniques and regular foot hygiene. Discussed the chronic nature of the condition and importance of adherence to treatment. Follow-up in one month to assess nail improvement and discuss potential systemic treatment if needed."],
    [1000050, "Middle-aged male presenting with multiple erythematous nodules on the shins. Suspected erythema nodosum. Associated with recent streptococcal throat infection. Recommend throat culture and supportive care including NSAIDs and rest. Educate on potential triggers and symptom management.", "Throat culture ordered. NSAID prescription provided for pain and inflammation. Advised to rest and elevate legs. Follow-up in two weeks to review throat culture results and assess symptom improvement. Discussed potential need for further investigation if no improvement."],
    [1000051, "Elderly female with a solitary, firm, non-tender nodule on the forearm. Clinical suspicion of dermatofibroma. Lesion is asymptomatic. Recommend observation and educating patient on benign nature of the condition.", "Patient reassured about the benign nature of the lesion. Discussed signs of changes that would warrant re-evaluation, such as rapid growth or bleeding. Advised to avoid unnecessary trauma to the area. Follow-up in six months to reassess if desired."]
]
data = pd.DataFrame(df, columns=["case_id", "case_text", "reply_text"])

# TODO Loop through cases file to extract the text from cases and replies to return the sentences
# def process_cases(cases):
#     data = pd.DataFrame(    
#     case_id = 0,
#     case_text = 0,
#     reply_text = 0
#     )
#     return data

def get_embedding(case):
    embedding = client.embeddings.create(
    model="text-embedding-ada-002",
    input=case
    )
    return embedding.data[0].embedding

def calculate_cosine(cases):
    embeddings = [get_embedding(case) for case in cases]
    similarities = cosine_similarity(embeddings)
    return similarities, embeddings

def main():
    sentences = list(data['case_text'])
    similarities, embeddings = calculate_cosine(sentences)
    print(similarities)
    data['embeddings'] = embeddings
    data.to_csv("/home/hackathon_ai_api/data.csv", index=False) # Return a csv with the case_id, case_text, reply_text, embeddings

if __name__ == '__main__':
    main()
